version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
            #SKIP TEST SCRIPTS
      #- run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
